baseurl = "https://eseymour.me"
title = "Edward Seymour"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

#disqusShortname = "yourdiscussshortname"

[params]
    author = "Edward Seymour"
    info = "Web and Android Software Developer in El Paso, Texas"
    description = "Edward Seymour's personal website"
    keywords = "blog,developer,personal"
    avatarurl = "img/avatar.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    hidecredits = true
    hidecopyright = false

    rtl = false

    math = false
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Email"
    icon = "fas fa-envelope fa-2x"
    weight = 1
    url = "mailto:edward@eseymour.me"
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 2
    url = "https://github.com/eseymour/"
#[[params.social]]
#    name = "Gitlab"
#    icon = "fab fa-gitlab fa-2x"
#    weight = 2
#    url = "https://gitlab.com/johndoe/"
#[[params.social]]
#    name = "Twitter"
#    icon = "fab fa-twitter fa-2x"
#    weight = 3
#    url = "https://twitter.com/johndoe/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 3
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "Projects"
    weight = 2
    url = "/projects/"
[[menu.main]]
    name = "Resume"
    weight = 3
    url = "/pdf/eseymour-resume.pdf"
